admin:
  port: 9990

namers:
- kind:            io.l5d.marathon
  host:            master.mesos
  port:            8080
  experimental:    true
  useHealthCheck:  true

routers:
- protocol: http
  servers:
  - port:  80
    ip:    "0.0.0.0"
  baseDtab: |
    /marathon    => /#/io.l5d.marathon;
    /path        => /$/io.buoyant.http.domainToPathPfx/marathon;
    /domain      => /$/io.buoyant.http.subdomainOfPfx/marathon.mesos/path;
    /http/1.1/*  => /domain;
